name: My Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Download artifact from build
      uses: bettermarks/action-artifact-download@0.3.0
      with:
        repo: PuerNya/sing-box/tree/building
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: my-artifact
        rename: new-artifact-name    
        wait_seconds: 60  ￼Enter
